name: Send Email Notification
on:
  repository_dispatch:
    types: [send_email]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email via SendGrid
        env:
          SENDGRID_API_KEY: ${{ yNQ9sTL6QtaLWKagC1oywQ }}
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer $SENDGRID_API_KEY" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{
                "to": [{"email": "${{ github.event.client_payload.toEmail }}"}]
              }],
              "from": {"email": "noreply@yourdomain.com", "name": "Visitor Management"},
              "subject": "${{ github.event.client_payload.action == 'new_demand' && 'Nouvelle demande de visiteur' || github.event.client_payload.action == 'rh_approved' && 'Demande approuvée par RH' || github.event.client_payload.action == 'rh_rejected' && 'Demande refusée par RH' || github.event.client_payload.action == 'dir_approved' && 'Demande approuvée par Direction' || 'Demande refusée par Direction' }}",
              "content": [{
                "type": "text/html",
                "value": "<h2>${{ github.event.client_payload.action == 'new_demand' && 'Nouvelle demande de visiteur' || github.event.client_payload.action == 'rh_approved' && 'Demande approuvée par RH' || github.event.client_payload.action == 'rh_rejected' && 'Demande refusée par RH' || github.event.client_payload.action == 'dir_approved' && 'Demande approuvée par Direction' || 'Demande refusée par Direction' }}</h2><p>Une demande a été mise à jour :</p><p><strong>Visiteur :</strong> ${{ github.event.client_payload.visitorName }}</p><p><strong>Date :</strong> ${{ github.event.client_payload.visitorDate }}</p><p>Veuillez vérifier la demande sur <a href=\"https://visiteur-externe.firebaseapp.com\">le site</a>.</p>"
              }]
            }'
